// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVdPxYyyge8V4HcU7MAdfMbvnCqVxVlWk',
    appId: '1:495463397119:web:b74e018dfd4b9b523d3eca',
    messagingSenderId: '495463397119',
    projectId: 'tredo-fb589',
    authDomain: 'tredo-fb589.firebaseapp.com',
    storageBucket: 'tredo-fb589.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADU0PjEfN1K9ISBFZNMce614pnfPefCxU',
    appId: '1:495463397119:android:c03fbac4b014b1633d3eca',
    messagingSenderId: '495463397119',
    projectId: 'tredo-fb589',
    storageBucket: 'tredo-fb589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANxkOruXZpdqGkgKol_8T0zaWT7rodAg8',
    appId: '1:495463397119:ios:4311c0156f56125d3d3eca',
    messagingSenderId: '495463397119',
    projectId: 'tredo-fb589',
    storageBucket: 'tredo-fb589.appspot.com',
    iosBundleId: 'com.example.flutterWrapArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANxkOruXZpdqGkgKol_8T0zaWT7rodAg8',
    appId: '1:495463397119:ios:4311c0156f56125d3d3eca',
    messagingSenderId: '495463397119',
    projectId: 'tredo-fb589',
    storageBucket: 'tredo-fb589.appspot.com',
    iosBundleId: 'com.example.flutterWrapArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVdPxYyyge8V4HcU7MAdfMbvnCqVxVlWk',
    appId: '1:495463397119:web:20fb7ec9969f81953d3eca',
    messagingSenderId: '495463397119',
    projectId: 'tredo-fb589',
    authDomain: 'tredo-fb589.firebaseapp.com',
    storageBucket: 'tredo-fb589.appspot.com',
  );

}